env:
  es6: true
  node: true
parser: "babel-eslint"
extends:
  - 'plugin:react/recommended'
  - google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {
  "no-invalid-this": 0,
  "require-jsdoc" : off,
  "linebreak-style": off,
  "max-len": [2,120],
}
